info:
  name: Exclusão de uma configuração de banco de horas
  type: http
  seq: 4
  tags:
    - Banco de Horas

http:
  method: DELETE
  url: "{{baseUrl}}/api/v1/bancohoras/configuracao"
  headers:
    - name: SISTEMAID
      value: "19"
  body:
    type: json
    data: |-
      {
        "v_configuracao_id": 123456
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Exclusão realizada com sucesso
    request:
      url: "{{baseUrl}}/api/v1/bancohoras/configuracao"
      method: DELETE
      headers:
        - name: SISTEMAID
          value: "19"
      body:
        type: json
        data: |-
          {
            "v_configuracao_id": 123456
          }
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "sucesso": true,
            "status": 200,
            "mensagem": "Registro apagado com sucesso",
            "retorno": []
          }
  - name: 401 Response
    description: Erro autenticação
    request:
      url: "{{baseUrl}}/api/v1/bancohoras/configuracao"
      method: DELETE
      headers:
        - name: SISTEMAID
          value: "19"
      body:
        type: json
        data: |-
          {
            "v_configuracao_id": 123456
          }
    response:
      status: 401
      statusText: Unauthorized
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: ""
  - name: 422 Response
    description: Erro de validação
    request:
      url: "{{baseUrl}}/api/v1/bancohoras/configuracao"
      method: DELETE
      headers:
        - name: SISTEMAID
          value: "19"
      body:
        type: json
        data: |-
          {
            "v_configuracao_id": 123456
          }
    response:
      status: 422
      statusText: Unprocessable Entity
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "sucesso": false,
            "status": 422,
            "mensagem": "The dados.0.descricao field must not be greater than 40 characters.",
            "erros": {
              "dados.0.descricao": [
                "The dados.0.descricao field must not be greater than 40 characters."
              ]
            },
            "retorno": null
          }

docs: "Remove uma configuração com base no v_configuracao_id (ID do banco de horas no sistema Único/Visual), e sistema_id (obtido a partir do header da request, passado SISTEMAID). ATENÇÃO: É importante que o parâmetro SISTEMAID seja sempre passado para garantir a correta associação da configuração ao sistema desejado. A operação remove DEFINITIVAMENTE o registro, não há como recuperá-lo após a alteração."
